version: '3.8'

services:
    web:
        command: > # Sleeping for 10 seconds ensures postgres is done building in time
          bash -c "sleep 10 &&
          python manage.py test --no-input"
        restart: "no"
