version: '3.8'

services:
    web:
        build: ./services/app
        command: [./start.sh]
        volumes:
            - ./services/app:/app/
            - static_files:/app/static
        expose:
            - 8000
        env_file:
            - ./.env/web.env
        depends_on:
            - db
        container_name: web
        # Required to recognize the db alias on docker-compose up
        restart: always
    db:
        image: postgres:14.1-alpine
        env_file:
            - ./.env/db.env
            - ./.env/web.env
        volumes:
            # https://stackoverflow.com/questions/1510104/where-to-store-application-data-non-user-specific-on-linux
            - postgres_data:/var/lib/postgresql/data
            - ./services/db/:/docker-entrypoint-initdb.d/
        container_name: postgres
    nginx:
        build: ./services/nginx
        ports:
            - 80:80
        volumes:
            - static_files:/static
        depends_on:
            - web
        container_name: nginx
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./services/certbot/data/certbot/conf:/etc/letsencrypt
            - ./services/certbot/www:/var/www/certbot
volumes:
    postgres_data:
    static_files:
