version: '3.8'

services:
    web:
        build: ./services/app
        command: [./start.sh]
        volumes:  
            - ./services/app:/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env/web.env
        depends_on:
            - db
        container_name: app
    db:
        image: postgres:14.1-alpine
        volumes:
            # https://stackoverflow.com/questions/1510104/where-to-store-application-data-non-user-specific-on-linux
            - postgres_data:/var/lib/postgresql/data
            - ./services/db/:/docker-entrypoint/initdb.d/
        container_name: postgres
volumes:
    postgres_data: