version: '3.8'

services:
    web:
        volumes:
            - static_files:/app/static
        env_file:
            - /home/pawnguild/secrets/.env/web.env
    db:
        env_file:
            - /home/pawnguild/secrets/.env/web.env
            - /home/pawnguild/secrets/.env/db.env
    nginx:
        volumes:
            - certs:/etc/letsencrypt
            - nginx_conf:/etc/nginx
        environment:
            - RUN_CERTBOT=true
            - CERTBOT_DOMAINS=pawntest.xyz,www.pawntest.xyz
            - CERTBOT_EMAIL=davidjbrady97@gmail.com
        command: ['sh', '/opt/command']
volumes:
    certs:
    nginx_conf: # Get's modified by the cert so we need to save it as well
