version: '3.8'


services:
    web:
        command: [./startup_scripts/start.dev.sh]
        environment:
          # https://stackoverflow.com/questions/6244382/how-to-automate-createsuperuser-on-django
          - DJANGO_SUPERUSER_USERNAME=admin  
          - DJANGO_SUPERUSER_PASSWORD=darkarisen
          - DJANGO_SUPERUSER_EMAIL=test@example.com
          