# Generated by Django 3.0.8 on 2020-07-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0002_auto_20200723_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ps3pawn',
            name='primary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ps3pawn',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ps4pawn',
            name='primary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ps4pawn',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='steampawn',
            name='primary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='steampawn',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='switchpawn',
            name='primary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='switchpawn',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xboxonepawn',
            name='primary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='xboxonepawn',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
