# Generated by Django 3.0.5 on 2020-04-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vocation', models.CharField(choices=[('Fighter', 'Fighter'), ('Warrior', 'Warrior'), ('Strider', 'Strider'), ('Ranger', 'Ranger'), ('Mage', 'Mage'), ('Sorcerer', 'Sorcerer')], max_length=20)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('primary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor'), ('None', 'None')], max_length=30)),
                ('secondary_inclination', models.CharField(max_length=30)),
            ],
        ),
    ]
