# Generated by Django 3.0.8 on 2020-07-16 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_url', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pawn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('vocation', models.CharField(choices=[('Fighter', 'Fighter'), ('Warrior', 'Warrior'), ('Strider', 'Strider'), ('Ranger', 'Ranger'), ('Mage', 'Mage'), ('Sorcerer', 'Sorcerer')], max_length=20)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('primary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor')], max_length=30)),
                ('secondary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor'), ('None', 'None')], max_length=30)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pawn_pictures/')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
