# Generated by Django 3.0.8 on 2020-07-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='platform',
            field=models.CharField(choices=[('Steam', 'Steam'), ('Switch', 'Switch'), ('XBOne', 'XBOne'), ('PS4', 'PS4'), ('PS4', 'PS4')], max_length=20, null=True),
        ),
    ]
