# Generated by Django 3.0.8 on 2020-07-22 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switchpawn',
            old_name='friend_code',
            new_name='friend_account_id',
        ),
        migrations.RenameField(
            model_name='switchpawn',
            old_name='pawn_code',
            new_name='pawn_id',
        ),
    ]
