# Generated by Django 3.0.8 on 2020-07-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steampawn',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='switchpawn',
            name='platform',
        ),
    ]
