# Generated by Django 3.0.5 on 2020-06-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0002_auto_20200616_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pawn',
            unique_together=set(),
        ),
    ]
