# Generated by Django 3.0.8 on 2020-07-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0002_userprofile_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='platform',
            field=models.CharField(choices=[('Steam', 'Steam'), ('Switch', 'Switch'), ('XBOne', 'XBOne'), ('PS4', 'PS4'), ('PS4', 'PS4')], default='Steam', max_length=20),
            preserve_default=False,
        ),
    ]
