# Generated by Django 3.0.5 on 2020-06-17 05:47

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pawnlisting', '0003_auto_20200616_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='created_by',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
