# Generated by Django 3.0.8 on 2020-07-22 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0003_xboxonepawn'),
    ]

    operations = [
        migrations.CreateModel(
            name='PS4Pawn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('vocation', models.CharField(choices=[('Fighter', 'Fighter'), ('Warrior', 'Warrior'), ('Strider', 'Strider'), ('Ranger', 'Ranger'), ('Mage', 'Mage'), ('Sorcerer', 'Sorcerer')], max_length=20)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('primary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor')], max_length=30)),
                ('secondary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor'), ('None', 'None')], default='None', max_length=30)),
                ('tertiary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor'), ('None', 'None')], default='None', max_length=30)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pawn_pictures/')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PS3Pawn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('vocation', models.CharField(choices=[('Fighter', 'Fighter'), ('Warrior', 'Warrior'), ('Strider', 'Strider'), ('Ranger', 'Ranger'), ('Mage', 'Mage'), ('Sorcerer', 'Sorcerer')], max_length=20)),
                ('level', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('primary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor')], max_length=30)),
                ('secondary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor'), ('None', 'None')], default='None', max_length=30)),
                ('tertiary_inclination', models.CharField(choices=[('Scather', 'Scather'), ('Medicant', 'Medicant'), ('Mitigator', 'Mitigator'), ('Challenger', 'Challenger'), ('Utilitarian', 'Utilitarian'), ('Guardian', 'Guardian'), ('Nexus', 'Nexus'), ('Pioneer', 'Pioneer'), ('Acquisitor', 'Acquisitor'), ('None', 'None')], default='None', max_length=30)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pawn_pictures/')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.TextField(choices=[('DD', 'DD'), ('Dark Arisen', 'Dark Arisen')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
