# Generated by Django 3.0.8 on 2020-07-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0005_auto_20200722_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ps3pawn',
            name='psn',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='ps4pawn',
            name='psn',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='xboxonepawn',
            name='gamertag',
            field=models.CharField(max_length=15),
        ),
    ]
