# Generated by Django 3.0.5 on 2020-07-10 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pawnlisting', '0007_auto_20200626_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawn',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
