# Generated by Django 3.0.5 on 2020-07-10 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0008_auto_20200710_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 1, 50, 11, 947561, tzinfo=utc)),
        ),
    ]
