# Generated by Django 3.0.5 on 2020-07-10 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0009_pawn_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawn',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
