# Generated by Django 3.0.8 on 2020-07-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='steam_profile',
            field=models.CharField(max_length=150),
        ),
    ]
