# Generated by Django 3.0.8 on 2020-07-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawnlisting', '0013_auto_20200715_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='steam_profile',
            new_name='steam_url',
        ),
    ]
