from .base import *  # noqa: F401, F403

ALLOWED_HOSTS = ["www.pawnguild.xyz", "137.184.81.130"]
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_PRELOAD = True


EMAIL_USE_TLS = True
EMAIL_PAGE_DOMAIN = ALLOWED_HOSTS[0] + "/"
