# https://github.com/marketplace/actions/run-black-formatter
name: black-action

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]


jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --exclude migrations/"