name: Deploy to production - digital ocean

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pawnguild
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ -d "pawnguild" ]; then
              git clone https://github.com/pawnguild/pawnguild
            fi
            cd pawnguild
            git pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
            docker-compose down
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
