# https://github.com/marketplace/actions/python-flake8-lint
name: flake8 Lint

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          exclude: "**/migrations/"
          max-line-length: "88"
